services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: nakama
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d nakama"]
      interval: 5s
      timeout: 5s
      retries: 5

  nakama:
    image: heroiclabs/nakama:3.22.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address local:local@postgres:5432/nakama &&
        exec /nakama/nakama --name nakama1 --database.address local:local@postgres:5432/nakama --logger.level DEBUG
    volumes:
      - ./modules:/nakama/data/modules
    ports:
      - "7350:7350"
      - "7351:7351"
    depends_on:
      postgres:
        condition: service_healthy
